### ISSUE TITLE
Unirest versi 2 tidak dapat jalan

### ISSUE THREAD

**Issue by mrsnax** [hok00age/rajaongkir-php#1]
Sesuai dengan requirment membutuhkan Unirest v.1.2

Apabila dimasukan versi 2.x, <b>Maka muncul error "Unires" Class Not found.</b>

Mohon masukan di deskripsi dibutuhkan <b>Unirest 1.2</b> agar tidak membuat para developer bingung untuk memilih Unirest nya.

Terima Kasih

**Comment by hok00age** [comment]
Dependency Unirest v1.2 sudah saya define di composer.json, sehingga otomatis akan terinstal ketika menginstal rajaongkir-php. Anda tidak perlu menginstal Unirest secara manual.

Thanks.

**Comment by mrsnax** [comment]
Back to old school, semua developer belum tentu menggunakan composser.json

**Comment by hok00age** [comment]
Deskripsi sudah dimasukkan.

Thanks.
