### ISSUE TITLE
Tanya Pengambilan Spefisik untuk Layanan

### ISSUE THREAD

**Issue by mrsnax** [hok00age/rajaongkir-php#2]
Dear, Tim RajaOngkir

Saya mau tanya bagaimana caranya saya mau ambil results cost hanya OKE dan YES sedangkan diluar itu tidak keambil dalam array.

Trims

**Comment by hok00age** [comment]
Salah kamar gan. Silakan hubungi lewat [Halaman kontak RajaOngkir](http://rajaongkir.com/kontak)

Thanks.
