### ISSUE TITLE
apakah support service terbaru?

### ISSUE THREAD

**Issue by handoyo** [hok00age/rajaongkir-php#3]
Terima kasih atas lPHP Class gratis nya buat ambil data dari rajaongkir. Saya mau tanya, sekarang rajaongkir ada 2 macam layanan. Starter dan Basic, yang ingin saya tanyakan apakah hanya perlu tambahin /starter atau /basic di belakang http://rajaongkir.com/api/? Dan apakah lisensi dari class ini? Apakah boleh dimodif serta dirubah namespacenya? Makasih.

**Comment by hok00age** [comment]
Tentu saja Anda bisa mem-fork dan membuat pull request, sehingga lib composer juga ikut terupdate. Anda juga bisa memodifikasi class ini untuk kepentingan Anda pribadi :)

Thanks.

**Comment by handoyo** [comment]
Makasih banyak mas. :)

Pada 13 April 2015 21.09, Damar Riyadi notifications@github.com menulis:
